<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\DB;

class FuctionsSeed extends Seeder
{
    private function encodeIdToString($id, $length = 10)
    {
        $id = (int)$id;
        $characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        $saltLength = $length - strlen((string)$id) - 2;
        $salt = '';
        for ($i = 0; $i < max(4, $saltLength); $i++) {
            $salt .= $characters[rand(0, strlen($characters) - 1)];
        }
        $combined = $salt . '-' . $id;
        return base64_encode($combined);
    }
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $features = [
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Luxury, elegant and seamless design",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Revolutionary technology, ACTILIGHT, ridding both visible                   and invisible waste",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hybrid Ecology System
    - WATER SAVING dual flush 3.8 / 3L
    - Minimum required water pressure only at 0.05MPa (Dynamic)",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST, a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps toilet bowl and nozzle clean by preventing bacteria with sanitizing effect",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto Soft light function usable for night time usage",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatically cleans the wand",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "AIR-IN WONDERWAVE cleansing provides comfort and eco-friendliness",
                "model_id" => "RDJEbVp0ZC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Luxury, elegant and seamless design",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hybrid Ecology System
    - WATER SAVING dual flush 3.8 / 3L
    - Minimum required water pressure only at 0.05MPa (Dynamic)",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST, a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps toilet bowl and nozzle clean by preventing bacteria with sanitizing effect",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto Soft light function usable for night time usage",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatically cleans the wand",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "AIR-IN WONDERWAVE cleansing provides comfort and eco-friendliness",
                "model_id" => "SGN1ZkRlYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Luxury, elegant and seamless design",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hybrid Ecology System
    - WATER SAVING dual flush 3.8 / 3L
    - Minimum required water pressure only at 0.05MPa (Dynamic)",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST, a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps toilet bowl and nozzle clean by preventing bacteria with sanitizing effect",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto Soft light function usable for night time usage",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatically cleans the wand",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "AIR-IN WONDERWAVE cleansing provides comfort and eco-friendliness",
                "model_id" => "VTJqWHJjMS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "New TORNADO FLUSH uses less water to produce powerful streams of water that travels along a hairpin curve of new RIMLESS DESIGN bowl creating a 360 degree of cleaning power that washes every spot",
                "model_id" => "Z1lodE9Mbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST, a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "Z1lodE9Mbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ not only keeps toilet bowl and nozzle clean by preventing bacterial with sanitizing effect but is also sprayed under the seat to prevent other accumulated waste, ensures a long-lasting cleanliness",
                "model_id" => "Z1lodE9Mbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatic operation: Lid opens, closes and toilet flushes when sensor is activated",
                "model_id" => "Z1lodE9Mbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "AIR-IN WONDERWAVE uses air rich water droplets to produce comfortable cleaning sensation",
                "model_id" => "Z1lodE9Mbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "Z1lodE9Mbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "Z1lodE9Mbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "Z1lodE9Mbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "New TORNADO FLUSH uses less water to produce powerful streams of water that travels along a hairpin curve of new RIMLESS DESIGN bowl creating a 360 degree of cleaning power that washes every spot",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],






            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST, a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ not only keeps toilet bowl and nozzle clean by preventing bacterial with sanitizing effect but is also sprayed under the seat to prevent other accumulated waste, ensures a long-lasting cleanliness",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatic operation: Lid opens, closes and toilet flushes when sensor is activated",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "AIR-IN WONDERWAVE uses air rich water droplets to produce comfortable cleaning sensation",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hybrid Ecology System - WATER SAVING",
                "model_id" => "c3hhWUE3Ri0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "New TORNADO FLUSH uses less water to produce powerful streams of water that travels along a hairpin curve of new RIMLESS DESIGN bowl creating a 360 degree of cleaning power that washes every spot",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST, a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ not only keeps toilet bowl and nozzle clean by preventing bacterial with sanitizing effect but is also sprayed under the seat to prevent other accumulated waste, ensures a long-lasting cleanliness",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatic operation: Lid opens, closes and toilet flushes when sensor is activated",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "AIR-IN WONDERWAVE uses air rich water droplets to produce comfortable cleaning sensation",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hybrid Ecology System - WATER SAVING",
                "model_id" => "Mm1hdlB0YS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "New TORNADO FLUSH uses less water to produce powerful streams of water that travels along a hairpin curve of new RIMLESS DESIGN bowl creating a 360 degree of cleaning power that washes every spot",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST, a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ not only keeps toilet bowl and nozzle clean by preventing bacterial with sanitizing effect but is also sprayed under the seat to prevent other accumulated waste, ensures a long-lasting cleanliness",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatic operation: Lid opens, closes and toilet flushes when sensor is activated",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "AIR-IN WONDERWAVE uses air rich water droplets to produce comfortable cleaning sensation",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hybrid Ecology System - WATER SAVING",
                "model_id" => "emYyVFNqUS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "New TORNADO FLUSH uses less water to produce powerful streams of water that travels along a hairpin curve of new RIMLESS DESIGN bowl creating a 360 degree of cleaning power that washes every spot",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST, a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ not only keeps toilet bowl and nozzle clean by preventing bacterial with sanitizing effect but is also sprayed under the seat to prevent other accumulated waste, ensures a long-lasting cleanliness",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatic operation: Lid opens, closes and toilet flushes when sensor is activated",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "AIR-IN WONDERWAVE uses air rich water droplets to produce comfortable cleaning sensation",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hybrid Ecology System - WATER SAVING",
                "model_id" => "Y1Y1TlZzNS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing with less amount of water",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Soft closing seat and cover",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps nozzle clean with sanitizing effect against bacteria",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with rear, oscillating & pulsating cleansing function",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Temperature control HEATED SEAT",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "WjJIZTkxcS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing with less amount of water",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Soft closing seat and cover",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps nozzle clean with sanitizing effect against bacteria",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with rear, oscillating & pulsating cleansing function",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Temperature control HEATED SEAT",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "MnptdEpwbi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "aE5ZVG9EMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing with less amount of water",
                "model_id" => "aE5ZVG9EMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "aE5ZVG9EMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps nozzle and bowl clean with sanitizing effect against bacteria",
                "model_id" => "aE5ZVG9EMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with rear, front and oscillating & pulsating cleansing function",
                "model_id" => "aE5ZVG9EMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Temperature control HEATED SEAT",
                "model_id" => "aE5ZVG9EMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "aE5ZVG9EMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto lid opening and closing",
                "model_id" => "aE5ZVG9EMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "RFk3TTlnaC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing with less amount of water",
                "model_id" => "RFk3TTlnaC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "RFk3TTlnaC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps nozzle and bowl clean with sanitizing effect against bacteria",
                "model_id" => "RFk3TTlnaC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with rear, front and oscillating & pulsating cleansing function",
                "model_id" => "RFk3TTlnaC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Temperature control HEATED SEAT",
                "model_id" => "RFk3TTlnaC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "RFk3TTlnaC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],





            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto lid opening and closing",
                "model_id" => "RFk3TTlnaC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Unique sculpted design, high profile One-Piece Toilet",
                "model_id" => "bWZab3hLby0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology:
super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "bWZab3hLby0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "bWZab3hLby0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN, seamless easy-clean bowl design",
                "model_id" => "bWZab3hLby0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Smart Toilet with WASHLET unit",
                "model_id" => "TlltVGtYei0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO Flushing for powerful flushing effect with less amount of water",
                "model_id" => "TlltVGtYei0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS bowl design ensures easy cleaning and ultimate hygiene",
                "model_id" => "TlltVGtYei0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT prevents debris on toilet surface",
                "model_id" => "TlltVGtYei0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with comfortable rear, front, and oscillating cleansing functions",
                "model_id" => "TlltVGtYei0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto lid opening and closing function",
                "model_id" => "TlltVGtYei0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto Flushing Function",
                "model_id" => "TlltVGtYei0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST water is sprayed inside the toilet bowl to make it difficult for dirt to adhere",
                "model_id" => "TlltVGtYei0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps nozzle and bowl clean with sanitizing effect against bacteria",
                "model_id" => "SjcySUlLQy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with rear, front and oscillating & pulsating cleansing function",
                "model_id" => "SjcySUlLQy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Temperature control HEATED SEAT",
                "model_id" => "SjcySUlLQy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "SjcySUlLQy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "SjcySUlLQy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto lid opening and closing",
                "model_id" => "SjcySUlLQy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps nozzle and bowl clean with sanitizing effect against bacteria",
                "model_id" => "enBjSVFJVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with rear, front and oscillating & pulsating cleansing function",
                "model_id" => "enBjSVFJVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Temperature control HEATED SEAT",
                "model_id" => "enBjSVFJVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "enBjSVFJVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto lid opening and closing",
                "model_id" => "enBjSVFJVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps nozzle clean with sanitizing effect against bacterial",
                "model_id" => "UWRDaW9JMy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with rear, front and oscillating & pulsating cleansing function",
                "model_id" => "UWRDaW9JMy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Temperature control HEATED SEAT",
                "model_id" => "UWRDaW9JMy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "UWRDaW9JMy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "UWRDaW9JMy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ keeps nozzle clean with sanitizing effect against bacterial",
                "model_id" => "MkdIQ3d1Sy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with rear, front and oscillating & pulsating cleansing function",
                "model_id" => "MkdIQ3d1Sy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Temperature control HEATED SEAT",
                "model_id" => "MkdIQ3d1Sy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST a fine spray of mist making it difficult for dirt to adhere",
                "model_id" => "MkdIQ3d1Sy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "MkdIQ3d1Sy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ spreads out and keeps clean toilet bowl and nozzle by preventing bacterial with sanitizing effect",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto lid opening and closing",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Maximized comfort function with new wide front and pulsating cleansing",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with comfortable rear, front and oscillating cleansing functions",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Build-in with Motion Sensor - Microwave technology",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Infrared Sensor for remote control capabilities",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "ZHBYVHpWZi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ spreads out and keeps clean toilet bowl and nozzle by preventing bacterial with sanitizing effect",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto lid opening and closing",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Maximized comfort function with new wide front and pulsating cleansing",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with comfortable rear, front and oscillating cleansing functions",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Build-in with Motion Sensor - Infrared technology",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Infrared Sensor for remote control capabilities",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "Q2N0VW44Mi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ spreads out and keeps the nozzle clean by preventing bacteria with sanitizing effect",
                "model_id" => "WDBjMEY5Ui0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST water is sprayed inside the toilet bowl to make it difficult for dirt to adhere",
                "model_id" => "WDBjMEY5Ui0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Maximized comfort function with pulsating cleansing",
                "model_id" => "WDBjMEY5Ui0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with comfortable rear, front and oscillating cleansing functions",
                "model_id" => "WDBjMEY5Ui0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "WDBjMEY5Ui0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "WDBjMEY5Ui0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "WDBjMEY5Ui0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ spreads out and keeps the nozzle clean by preventing bacteria with sanitizing effect",
                "model_id" => "SVFobDROVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST water is sprayed inside the toilet bowl to make it difficult for dirt to adhere",
                "model_id" => "SVFobDROVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Maximized comfort function with pulsating cleansing",
                "model_id" => "SVFobDROVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with comfortable rear, front and oscillating cleansing functions",
                "model_id" => "SVFobDROVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "SVFobDROVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "SVFobDROVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "SVFobDROVC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ spreads out and keeps the nozzle clean by preventing bacteria with sanitizing effect",
                "model_id" => "T3hjTnplYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST water is sprayed inside the toilet bowl to make it difficult for dirt to adhere",
                "model_id" => "T3hjTnplYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Maximized comfort function with new wide front and pulsating cleansing",
                "model_id" => "T3hjTnplYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with comfortable rear, front and oscillating cleansing functions",
                "model_id" => "T3hjTnplYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "T3hjTnplYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "T3hjTnplYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "T3hjTnplYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ spreads out and keeps the nozzle clean by preventing bacteria with sanitizing effect",
                "model_id" => "UnVsb0xTTC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST water is sprayed inside the toilet bowl to make it difficult for dirt to adhere",
                "model_id" => "UnVsb0xTTC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with comfortable rear, front and oscillating cleansing functions",
                "model_id" => "UnVsb0xTTC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "UnVsb0xTTC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "UnVsb0xTTC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "UnVsb0xTTC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "EWATER+ spreads out and keeps the nozzle clean by preventing bacteria with sanitizing effect",
                "model_id" => "S1ZHY1ZocS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "PREMIST water is sprayed inside the toilet bowl to make it difficult for dirt to adhere",
                "model_id" => "S1ZHY1ZocS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Fully equipped with comfortable rear, front and oscillating cleansing functions",
                "model_id" => "S1ZHY1ZocS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Adjustable WARM AIR DRYING",
                "model_id" => "S1ZHY1ZocS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "HEATED SEAT with temperature control",
                "model_id" => "S1ZHY1ZocS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Auto powerful DEODORIZER activates after every usage",
                "model_id" => "S1ZHY1ZocS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Rear cleaning with bidet functions",
                "model_id" => "QnFlYzJpcC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hygienic self cleaning nozzle",
                "model_id" => "QnFlYzJpcC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Soft closing seat and cover",
                "model_id" => "QnFlYzJpcC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy remove for cleaning",
                "model_id" => "QnFlYzJpcC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy Installation",
                "model_id" => "QnFlYzJpcC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "No AC Power required",
                "model_id" => "QnFlYzJpcC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Rear cleaning with bidet functions",
                "model_id" => "ajUxQVh2ay0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hygienic self cleaning nozzle",
                "model_id" => "ajUxQVh2ay0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Soft closing seat and cover",
                "model_id" => "ajUxQVh2ay0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy remove for cleaning",
                "model_id" => "ajUxQVh2ay0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy Installation",
                "model_id" => "ajUxQVh2ay0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "No AC Power required",
                "model_id" => "ajUxQVh2ay0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Rear cleaning with bidet functions",
                "model_id" => "clJ1OEdhRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hygienic self cleaning nozzle",
                "model_id" => "clJ1OEdhRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Soft closing seat and cover",
                "model_id" => "clJ1OEdhRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy remove for cleaning",
                "model_id" => "clJ1OEdhRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy Installation",
                "model_id" => "clJ1OEdhRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "No AC Power required",
                "model_id" => "clJ1OEdhRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Rear cleaning with bidet functions",
                "model_id" => "YnNjcUt1dS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hygienic self cleaning nozzle",
                "model_id" => "YnNjcUt1dS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Soft closing seat and cover",
                "model_id" => "YnNjcUt1dS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy remove for cleaning",
                "model_id" => "YnNjcUt1dS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy Installation",
                "model_id" => "YnNjcUt1dS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "No AC Power required",
                "model_id" => "YnNjcUt1dS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],




            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Rear cleaning with bidet functions",
                "model_id" => "STltRzJDMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Hygienic self cleaning nozzle",
                "model_id" => "STltRzJDMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Soft closing seat and cover",
                "model_id" => "STltRzJDMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy remove for cleaning",
                "model_id" => "STltRzJDMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy Installation",
                "model_id" => "STltRzJDMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "No AC Power required",
                "model_id" => "STltRzJDMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Unique sculpted design, high profile One-Piece Toilet",
                "model_id" => "ZGJGdVBhYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "ZGJGdVBhYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "ZGJGdVBhYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN, seamless easy-clean bowl design",
                "model_id" => "ZGJGdVBhYi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Stylish design, high profile One Piece Toilet",
                "model_id" => "dHZONm8wUi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "dHZONm8wUi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "dHZONm8wUi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "dHZONm8wUi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Dual Flush System",
                "model_id" => "dHZONm8wUi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "dHZONm8wUi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "The AP Series suite: Matching toilets, lavatories and bidets",
                "model_id" => "eDgxQXZCVS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Unique sculpted design, low profile One-Piece Toilet",
                "model_id" => "eDgxQXZCVS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Skirted styling with concealed trapway for easy cleaning",
                "model_id" => "eDgxQXZCVS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Upgrade with a Softclose Seat & Cover or WASHLET",
                "model_id" => "eDgxQXZCVS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "The Avante suite: Matching toilets, lavatories and bidets",
                "model_id" => "M1FlSFhoRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Unique sculpted design, low profile One-Piece Toilet",
                "model_id" => "M1FlSFhoRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Skirted styling with concealed trapway for easy cleaning",
                "model_id" => "M1FlSFhoRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Upgrade with a Softclose Seat & Cover or WASHLET",
                "model_id" => "M1FlSFhoRy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Stylish design, high profile One Piece Toilet",
                "model_id" => "dE92TjFxYS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],



            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "dE92TjFxYS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "dE92TjFxYS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "dE92TjFxYS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "dE92TjFxYS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Unique sculpted design, high profile One-Piece Toilet",
                "model_id" => "ck1jOEhlby0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "ck1jOEhlby0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Upgrade with a Softclose Seat & Cover or WASHLET",
                "model_id" => "ck1jOEhlby0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Stylish design, high profile One Piece Toilet",
                "model_id" => "bWVBbDNPdC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "bWVBbDNPdC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "bWVBbDNPdC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "bWVBbDNPdC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Dual Flush System",
                "model_id" => "bWVBbDNPdC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "bWVBbDNPdC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Unique sculpted design, high profile One-Piece Toilet",
                "model_id" => "Snh0MzdrNi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "Snh0MzdrNi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Upgrade with a Softclose Seat & Cover or WASHLET",
                "model_id" => "Snh0MzdrNi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Stylish and sleek design, one-piece toilet",
                "model_id" => "RWZmWmt5NS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Dual Flush System",
                "model_id" => "RWZmWmt5NS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatic flush enables Hands-free usage, increasing hygiene",
                "model_id" => "UHZuYWphRi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Push button - Enable users to flush manually",
                "model_id" => "UHZuYWphRi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Constant Flow Valve for stable flow volume and performance, easy to install",
                "model_id" => "UHZuYWphRi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "LED Indicator to reflect different stages.",
                "model_id" => "UHZuYWphRi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "UHZuYWphRi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT technology: super smooth, ion barrier glaze for a clean toilet bow",
                "model_id" => "UHZuYWphRi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],


            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "UHZuYWphRi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Elegant styling exclusively for Basic + design suite",
                "model_id" => "OHU2aTk5bi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNDO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "OHU2aTk5bi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "OHU2aTk5bi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Dual flush system",
                "model_id" => "OHU2aTk5bi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "OHU2aTk5bi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Softclose Seat & Cover",
                "model_id" => "OHU2aTk5bi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "N0hycDhYMi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy cleaning wall hung design",
                "model_id" => "N0hycDhYMi0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "Z21Edm9FZS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy cleaning wall hung design",
                "model_id" => "Z21Edm9FZS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatic flush enables Hands-free usage, increasing hygiene",
                "model_id" => "RWFybE8ydS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],


            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Push button - Enable users to flush manually",
                "model_id" => "RWFybE8ydS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Automatic flush enables Hands-free usage, increasing hygiene",
                "model_id" => "RWFybE8ydS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Push button - Enable users to flush manually",
                "model_id" => "RWFybE8ydS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy installation and Saves space, as the Cistern is not needed",
                "model_id" => "NTFldlhiYy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Easy installation and Saves space",
                "model_id" => "aGFma0VOMC0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Unique sculpted design, high profile Close Coupled Toilet",
                "model_id" => "TUpjVmI2OS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Wall-Faced Styling with concealed trapway for easy cleaning",
                "model_id" => "TUpjVmI2OS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "TUpjVmI2OS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "TUpjVmI2OS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "TUpjVmI2OS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Dual Flush System",
                "model_id" => "TUpjVmI2OS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "TUpjVmI2OS0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Unique sculpted design, high profile Close Coupled Toilet",
                "model_id" => "SDVSeU04Zy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Wall-Faced Styling with concealed trapway for easy cleaning",
                "model_id" => "SDVSeU04Zy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "TORNADO FLUSH for powerful flushing effect with less amount of water",
                "model_id" => "SDVSeU04Zy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "CEFIONTECT Technology: super smooth, ion barrier glazing for a clean toilet bowl",
                "model_id" => "SDVSeU04Zy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "RIMLESS DESIGN bowl ensures easy cleaning and ultimate hygiene",
                "model_id" => "SDVSeU04Zy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "Dual Flush System",
                "model_id" => "SDVSeU04Zy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],
            [
                "uuid" => $this->encodeIdToString(rand(0, 9999)),
                "description" => "WATER SAVING",
                "model_id" => "SDVSeU04Zy0x",
                "created_at" => Today(),
                "updated_at" => Today(),
            ],

        ];


        DB::table('features')->insert($features);
    }
}
